### ISSUE TITLE
可否打一个.net core 2.1 runtime 的包，包含libgdiplus库的？

### ISSUE THREAD

**Issue by xBoo** [lonwern/aspnetcore-libgdiplus#1]
FROM microsoft/dotnet:2.1-runtime

RUN apt-get update \
    && apt-get -y install libgdiplus \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

**Comment by xBoo** [comment]
天朝的网络，你懂的，我这边死活打不成功。

**Comment by lonwern** [comment]
https://hub.docker.com/r/lonwern/dotnet-libgdiplus/
